sudo: required,
language: node_js
node_js:
  - "0.12"
before_install:
  - curl https://install.meteor.com/ | sh
  - meteor npm install
services:
  - mongodb
env:
  #- LAIKA_OPTIONS="-t 5000"
after_success:
  -  meteor build --directory ./
  -  ls ./
