sudo: required,
language: node_js
node_js:
  - "0.12"
before_install:
  - curl https://install.meteor.com/ | sh
  - meteor npm install
services:
  - docker
env:
  #- LAIKA_OPTIONS="-t 5000"
after_success:
  -  meteor build ./
  -  ls ./
  -  docker --version
  -  docker pull node:0.12
  -  docker build catsass19/sapporo:v1 .
  -  docker images
