#
# This is for Travis CI.
# - Every github commit triggers Travis CI to build a Docker image
# - For more information please visit:
#       https://travis-ci.org
#

sudo: required,
language: node_js
node_js:
  - "0.46"
before_install:
  - curl https://install.meteor.com/ | sh
  #- meteor npm install #This is not needed. We only need Meteor build
services:
  - docker
env:
  #- LAIKA_OPTIONS="-t 5000"
after_success:
  -  meteor build ./
  -  ls ./
  -  docker --version
  #-  docker pull node:0.10
  -  docker build -t sapporo/sapporo:0.$TRAVIS_BUILD_NUMBER .
  -  docker build -t sapporo/sapporo:latest .
  -  docker images
  -  docker run sapporo/sapporo:latest node /sapporo/bundle/main.js #If it's valid, it should throw the error of missing MongoDB URL
  -  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  -  docker push sapporo/sapporo:0.$TRAVIS_BUILD_NUMBER
  -  docker push sapporo/sapporo:latest
