#
# This is for Travis CI.
# - Every github commit triggers Travis CI to build a Docker image
# - For more information please visit:
#       https://travis-ci.org
#

sudo: required,
language: node_js
node_js:
  - "0.12"
before_install:
  - curl https://install.meteor.com/ | sh
  #- meteor npm install #This is not needed. We only need Meteor build
services:
  - docker
env:
  #- LAIKA_OPTIONS="-t 5000"
after_success:
  -  meteor build ./
  -  ls ./
  -  docker --version
  -  docker pull node:0.12
  -  docker build -t sapporo/sapporo:latest .
  #-  docker run catsass19/sapporo:v1 node /sapporo/bundle/main.js
  -  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  -  docker push sapporo/sapporo:latest
